services:
  lemmy:
    image: dockurr/lemmy
    container_name: lemmy
    ports:
      - 8536:8536
    environment:
      - RUST_LOG="warn"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    restart: always
    stop_grace_period: 1m
