services:
  lemmy:
    image: dockurr/lemmy
    container_name: lemmy
    environment:
      RUST_LOG: "warn"
    ports:
      - 8536:8536
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    restart: always
    stop_grace_period: 1m
